spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect