spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:/schema-test.sql';DB_CLOSE_DELAY=-1
    username: sa

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect